TCCESTOQUE/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using TCCESTOQUE.Interfaces.Service;
using TCCESTOQUE.Models;
using TCCESTOQUE.ViewModel;

namespace TCCESTOQUE.Controllers
{
    public class ClienteController : ControllerPai
    {
        private readonly IClienteService _cliService;

        public ClienteController(IClienteService context)
        {
            _cliService = context;
        }

        // GET: Cliente
        [Authorize]
        public IActionResult Index()
        {
            Autenticar();
            return View(_cliService.GetAll(ViewBag.usuarioId));
        }

        // GET: Cliente/Details/5
        [Authorize]
        public IActionResult Details(Guid? id)
        {
            Autenticar();
            if (id == null)
                return NotFound();

            var clienteModel = _cliService.GetOne(id);

            if (clienteModel == null)
                return NotFound();

            return View(clienteModel);
        }

        // GET: Cliente/Create
        [Authorize]
        public IActionResult Create()
        {
            Autenticar();
            return View();
        }

        // POST: Cliente/Create/VendedorId
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Create(ClienteViewModel cliVM)
        {
            Autenticar();
            var res = _cliService.PostCriacao(cliVM);
            if (!res.IsValid)
                return View(MostrarErros(res, cliVM));

            return RedirectToAction(nameof(Index));
        }

        // GET: Cliente/Edit/5/VendedorId
        [Authorize]
        public IActionResult Edit(Guid? id)
        {
            Autenticar();
            if (id == null)
                return NotFound();

            var clienteModel = _cliService.GetEdicao(id);
            if (clienteModel == null)
                return NotFound();

            return View(clienteModel);
        }

        // POST: Cliente/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Edit(Guid id, ClienteViewModel cliVM)
        {
            Autenticar();
            if (cliVM.ClienteId == Guid.Empty)
                return NotFound();

            var res = _cliService.PutEdicao(cliVM);
            if (!res.IsValid)
                return View(MostrarErros(res, cliVM));

            return RedirectToAction(nameof(Index));
        }

        // GET: Cliente/Delete/5
        [Authorize]
        public IActionResult Delete(Guid? id)
        {
            Autenticar();
            if (id == null)
                return NotFound();

            var clienteModel = _cliService.GetOne(id);

            if (clienteModel == null)
                return NotFound();

            return View(clienteModel);
        }

        // POST: Cliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult DeleteConfirmed(ClienteModel cliente)
        {
            Autenticar();
            var res = _cliService.PostExclusao(cliente.ClienteId);
            if (res)
                return RedirectToAction(nameof(Index));

            ViewBag.ErroExcluir = "Não é possivel deletar o cliente, ele está em alguma venda!";
            return View(_cliService.GetOne(cliente.ClienteId));
        }
    }
}

TCCESTOQUE/Controllers/EntradaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using TCCESTOQUE.Interfaces.Service;
using TCCESTOQUE.Models;

namespace TCCESTOQUE.Controllers
{
    public class EntradaController : ControllerPai
    {
        private readonly IEntradaService _entradaService;
        private readonly ISelectListService _selectListService;
        private readonly IProdutoService _produtoService;
        public EntradaController(IEntradaService context, ISelectListService selectListService, IProdutoService produtoService)
        {
            _entradaService = context;
            _selectListService = selectListService;
            _produtoService = produtoService;
        }

        // GET: Entrada
        public IActionResult Index()
        {
            Autenticar();
            return View(_entradaService.GetAll(ViewBag.usuarioId));
        }

        // GET: Entrada/Details/5
        public IActionResult Details(Guid? id)
        {
            Autenticar();
            var entrada = _entradaService.GetOne(id);
            if (entrada == null)
                return NotFound();

            return View(entrada);
        }

        // GET: Entrada/Create
        public IActionResult Create(Guid produtoId)
        {
            Autenticar();
            if (produtoId == Guid.Empty || _produtoService.GetOne(produtoId) == null || _produtoService.GetOne(produtoId).Inativo)
                return NotFound();
            ViewData["FornecedorId"] = _selectListService.SelectListFornecedor("FornecedorId", "NomeFantasia", ViewBag.usuarioId);
            ViewData["ProdutoId"] = produtoId;
            ViewData["ProdutoNome"] = _produtoService.GetOne(produtoId).Nome;
            ViewData["Medida"] = _produtoService.GetOne(produtoId).UnidadeMedida;
            return View();
        }

        // POST: Entrada/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EntradaModel entradaModel)
        {
            Autenticar();
            if (entradaModel.FornecedorId == Guid.Empty)
                ModelState.AddModelError("FornecedorId", "Selecione um fornecedor");

            if (ModelState.IsValid && entradaModel.ProdutoId != Guid.Empty)
            {
                _entradaService.PostEntrada(entradaModel);
                return RedirectToAction(nameof(Index));
            }
            ViewData["FornecedorId"] = _selectListService.SelectListFornecedor("FornecedorId", "NomeFantasia", entradaModel.FornecedorId, ViewBag.usuarioId);
            ViewData["ProdutoId"] = entradaModel.ProdutoId;
            ViewData["ProdutoNome"] = _produtoService.GetOne(entradaModel.ProdutoId).Nome;
            ViewData["Medida"] = _produtoService.GetOne(entradaModel.ProdutoId).UnidadeMedida;
            return View(entradaModel);
        }

        // GET: Entrada/Delete/5
        public IActionResult Delete(Guid? id)
        {
            Autenticar();
            var entrada = _entradaService.GetOne(id);
            if (entrada == null)
                return NotFound();

            return View(entrada);
        }

        // POST: Entrada/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(EntradaModel entradaModel)
        {
            Autenticar();
            var saida = _entradaService.CancelarEntrada(entradaModel);
            if (saida != "")
            {
                ModelState.AddModelError("", saida);
                return View(entradaModel);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

TCCESTOQUE/Views/Shared/_Layout-Externo.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>E-STOCK @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/geral.css" rel="stylesheet" />
    <link href="~/css/formularios.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>
<body class="bg-white">
    <header>
        <nav class="navbar navbar-expand-sm p-0 navbar-toggleable-sm navbar-dark bg-roxo">
            <div class="container-fluid py-2">                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul id="nav-externo" class="navbar-nav flex-grow-1 nav-divider"> 
                        <li class="nav-item">
                            <a class="btn btn-outline-light border-0" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-light border-0" asp-area="" asp-controller="Home" asp-action="Manual">Manual</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-light border-0" asp-controller="Vendedor" asp-action="Create">Cadastrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-light border-0" asp-controller="Vendedor" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid p-0">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer border-top box-shadow bg-white text-center">
        &copy; 2021 - E-STOCK
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-mask-plugin/jquery.mask.js" type="text/javascript"  asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TCCESTOQUE/Views/Shared/_Layout-Interno.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>E-STOCK @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/formularios.css" rel="stylesheet" />
    <link href="~/css/tabela.css" rel="stylesheet" />
    <link href="~/css/geral.css" rel="stylesheet" />
    <link href="~/css/descricao.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/home_logada.css" rel="stylesheet" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>
<body class="bg-white">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow p-0 mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img class="nav-logo" src="~/img/logo-box.png"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdownFornecedor" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Fornecedor
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Fornecedor" asp-action="CadastroFull">Cadastrar Fornecedor</a>
                                <a class="dropdown-item" asp-controller="Fornecedor" asp-action="Index">Meus Fornecedores</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdownProduto" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Produto
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Produto" asp-action="Create">Cadastrar Produto</a>
                                <a class="dropdown-item" asp-controller="Produto" asp-action="Index">Meu Estoque</a>
                                <a class="dropdown-item" asp-controller="Entrada" asp-action="Index">Histórico de entradas</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdownFornecedor" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Cliente
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Cliente" asp-action="Create">Cadastrar Cliente</a>
                                <a class="dropdown-item" asp-controller="Cliente" asp-action="Index">Meus Cliente</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdownFornecedor" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Venda
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Carrinho" asp-action="Details" asp-route-id="@ViewBag.usuarioId">Vender</a>
                                <a class="dropdown-item" asp-controller="Venda" asp-action="Index">Minhas vendas</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown mr-2">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Olá @ViewBag.usuario
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <form method="post">
                                    <input type="submit" value="Desconectar" class="dropdown-item" asp-controller="Vendedor" asp-action="Logout" />
                                </form>
                            </div>
                        </li>

                        <li class="my-sm-2 py-0">
                            <a class="btn-mold btn-roxo m-0" asp-controller="Carrinho" asp-action="Details" asp-route-id="@ViewBag.usuarioId">Vender</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer border-top box-shadow bg-white text-center">
        &copy; 2021 - E-STOCK
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-mask-plugin/jquery.mask.js" type="text/javascript" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TCCESTOQUE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TCCESTOQUE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TCCESTOQUE</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 nav-divider">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @{
                            if (!ViewBag.autenticado)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Vendedor" asp-action="Create">Cadastrar</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Vendedor" asp-action="Login">Login</a>
                                </li>
                            }

                            if (ViewBag.autenticado != null && ViewBag.autenticado)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Fornecedor" asp-action="Index">Fornecedor</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Produto" asp-action="Index">Estoque</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Venda" asp-action="Index">Vendas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Cliente" asp-action="Index">Cliente</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Entrada" asp-action="Index">Historico +</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Carrinho" asp-action="Details" asp-route-id="@ViewBag.usuarioId">Carrinho</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Vendedor" asp-action="Logout" asp-route-id="@ViewBag.usuarioId">Desconectar</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer bg-white text-center">
        &copy; 2021 - TCCESTOQUE - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-mask-plugin/jquery.mask.js" type="text/javascript"  asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>